let x = Number (prompt("сумма.введите первое число"))
    y = Number (prompt("введите второе число"))
    alert("сумма:" + (x + y))
    console.log(x + y)
let d = Number (prompt("вычитание. введите первое число")) 
    n = Number (prompt("введите второе число"))
    alert("разность:"+ (d - n))
    console.log (d - n)
let z = Number (prompt("умножение. введите первое число"))
    c = Number (prompt("введите второе число"))
    alert("произведение:" + (z * c))
    console.log (z * c)
let a = Number (prompt("деление. введите первое число")) 
    b = Number (prompt("введите второе число"))
    alert("частное:" + (a / b))
    console.log (a / b)
    